### ISSUE TITLE
Wrong timezone info from time.tzname in filewriter.FTFile.currenttime on Windows

### ISSUE THREAD

**Issue by pascaldreher** [nexdatas/tools#223]
Dear developers,

first of all thank you for all your amazing efforts! We are currently setting up a Tango Controls system in our ultrafast photoemissiom lab and would like to use the NXSDataWriter Tango server. While testing the server I stumbled across the following issue:

Upon excecuting the OpenFile() and CloseFile() commands of the NXSDataWriter server, the server throws the following exception

```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pytz\__init__.py", line 174, in timezone
    zone = ascii(zone)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pytz\__init__.py", line 59, in ascii
    s.encode('ASCII')  # Raise an exception if not ASCII
UnicodeEncodeError: 'ascii' codec can't encode character '\xe4' in position 11: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\nxswriter\NXSWriter.py", line 791, in CloseFile
    self.tdw.closeFile()
  File "C:\ProgramData\Anaconda3\lib\site-packages\nxswriter\TangoDataWriter.py", line 708, in closeFile
    self.__nxFile.close()
  File "C:\ProgramData\Anaconda3\lib\site-packages\nxstools\h5pywriter.py", line 501, in close
    unicode(self.currenttime())
  File "C:\ProgramData\Anaconda3\lib\site-packages\nxstools\filewriter.py", line 527, in currenttime
    tz = pytz.timezone(tzone)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pytz\__init__.py", line 177, in timezone
    raise UnknownTimeZoneError(zone)
pytz.exceptions.UnknownTimeZoneError: 'MitteleuropÃ¤ische Zeit'
```

This exception can be traced back to the call to `time.tzname` in `filewriter.FTFile.currenttime`, which returns `('Mitteleuropäische Zeit', 'Mitteleuropäische Sommerzeit')` on my machine. This returns obviously is not a standardized Olson/IANA timezone and the correct return value would have to be "Europe/Berlin". 

Whether this is a python bug or not, the `currenttime` routine could be fixed using `tzlocal.get_localzone()`, which returns the correct value on my machine, instead of the call to `time.tzname`.

I am currently using python 3.8.10 on a German version of Windows 10 64bit Build 19042.1110.

Cheers,
Pascal Dreher

**Comment by jkotan** [comment]
Dear Pascal Dreher,

thank you for pointing out the problem. I've just created PR #224 which should fix the problem. We test our packages on debian and ubuntu so we were not aware of this issue. I'm glad to here nxstools works on Windows. 
Please check if the fix  works for you.

Cheers,
Jan

**Comment by pascaldreher** [comment]
Dear Jan Kotanski,

I tested PR #224 on my machine and it seems to work. Thank you for the fix.

However, I believe the same fix also applies to `nxswriter.NXSFromXML.CreateFile.currenttime()`. Should I open an issue in this repo as well?

Best,
Pascal

**Comment by jkotan** [comment]
Dear Pascal,

Thanks. I will create PR also for nxswriter.

Best,
Jan

**Comment by jkotan** [comment]
Dear Pascal,

I've just merged the new PR for nxswriter to develop branch. Let me know if you have other issues. If not I will create new releases for nxstools and nxswriter next week

Best,
Jan
